version: '3'

services:

  mysql:
    image: mysql:5.7.21
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./mysql-initdb:/docker-entrypoint-initdb.d
    restart: always

  myadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: mysql
    ports:
      - "8001:80"
    depends_on:
      - mysql
    restart: always