CREATE DATABASE IF NOT EXISTS `django_jwt` DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
USE `django_jwt`;

SET @PREVIOUSFOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS;
SET FOREIGN_KEY_CHECKS = 0;

CREATE USER 'django-user'@'%' IDENTIFIED BY 'mydjango-password';
GRANT ALL PRIVILEGES ON *.* TO 'django-user'@'%';
FLUSH PRIVILEGES;